### ISSUE TITLE
Allow to skip "protect" backup

### ISSUE THREAD

**Issue by thib3113** [aessing/udm-backup-ftp#9]
In some cases (my case), unifi protect is not used . So, not backuped, and the folder `/mnt/data_ext/unifi-os/unifi-protect/backups:/backups/protect:` doesn't exist 

## Context
- UDM-pro
- unifi protect disabled (because use of another solution)

## Possible Implementation
check if $PROTECT_MOUNT is empty

---

Because of your contributing, I doesn't open a pull request, for the moment, but here is how I update the `on_boot.d/80-udm-backup-ftp.sh`
https://github.com/thib3113/udm-backup-ftp/commit/e2af2c3e53d9ff3a14b8acaa987298db564238d4

I've just move some informations in vars, and checking if  $SDN_MOUNT / $PROTECT_MOUNT is filled or not, and add the -v option depending . 

My only concerns is : for the moment, the only problem I saw (not sure), is "what about if I empty SDN_MOUNT" ?
I'm not sure, if the `-v` order is important, and correspond of the dockerFile `VOLUME` order ... In the worst case, the protect backup will be in `unifi` folder

**Comment by aessing** [comment]
Thanks @thib3113 for opening the issue.
Let me have a look at it.

I will contact you soon.

**Comment by aessing** [comment]
Hi @thib3113,

Thanks for your contribution.
Please open a PR for your change. I will merge them into the repo.

I found a few small things in your code I would like to ask you to change before merging:

 - You forgot the CRON_SCHEDULE in line 50. It should look like:
```shell
CRON_CMD="${CRON_SCHEDULE} ${CRON_CMD} ${BACKUP_IMG}"
```
-  Could you please remove the comment hash on line 54 and enable writing to the cronfile. So remove line 54 and line 53 should look like:
```shell
 echo "${CRON_CMD}" > ${CRON_FILE}
```

Also could you please remove the comment hash from line 35, as the standard schould be backup up both services. Perhaps you can add a comment, how to disable backup for  Protect.

Thanks 
Andre

**Comment by thib3113** [comment]
Hi @aessing , In fact, I just saw my first link is too specific ( link to a commit, and not the branch ) . 

I've done another commit just after commeting, because I forgot to take some changes from local .

About the ${CRON_SCHEDULE} , in fact I add it on line where I echo the cron to cron file . 

So, with that, I totally separe vars, and code . And we can say "stop to edit after line XXX" . 

But, it's as you prefer .

I'm preparing the PR
